# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtPdfWidgets import QPdfView
from PySide6.QtWidgets import (QApplication, QHBoxLayout, QHeaderView, QMainWindow,
    QMenu, QMenuBar, QSizePolicy, QSplitter,
    QStatusBar, QTabWidget, QTableWidget, QTableWidgetItem,
    QToolBar, QTreeView, QVBoxLayout, QWidget)
import rc_resources

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(805, 600)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        icon = QIcon()
        iconThemeName = u"document-open"
        if QIcon.hasThemeIcon(iconThemeName):
            icon = QIcon.fromTheme(iconThemeName)
        else:
            icon.addFile(u":/icons/images/document-open.svgz", QSize(), QIcon.Normal, QIcon.Off)

        self.actionOpen.setIcon(icon)
        self.actionQuit = QAction(MainWindow)
        self.actionQuit.setObjectName(u"actionQuit")
        icon1 = QIcon(QIcon.fromTheme(u"application-exit"))
        self.actionQuit.setIcon(icon1)
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        icon2 = QIcon(QIcon.fromTheme(u"help-about"))
        self.actionAbout.setIcon(icon2)
        self.actionAbout_Qt = QAction(MainWindow)
        self.actionAbout_Qt.setObjectName(u"actionAbout_Qt")
        self.actionZoom_In = QAction(MainWindow)
        self.actionZoom_In.setObjectName(u"actionZoom_In")
        icon3 = QIcon()
        iconThemeName = u"zoom-in"
        if QIcon.hasThemeIcon(iconThemeName):
            icon3 = QIcon.fromTheme(iconThemeName)
        else:
            icon3.addFile(u":/icons/images/zoom-in.svgz", QSize(), QIcon.Normal, QIcon.Off)

        self.actionZoom_In.setIcon(icon3)
        self.actionZoom_Out = QAction(MainWindow)
        self.actionZoom_Out.setObjectName(u"actionZoom_Out")
        icon4 = QIcon()
        iconThemeName = u"zoom-out"
        if QIcon.hasThemeIcon(iconThemeName):
            icon4 = QIcon.fromTheme(iconThemeName)
        else:
            icon4.addFile(u":/icons/images/zoom-out.svgz", QSize(), QIcon.Normal, QIcon.Off)

        self.actionZoom_Out.setIcon(icon4)
        self.actionPrevious_Page = QAction(MainWindow)
        self.actionPrevious_Page.setObjectName(u"actionPrevious_Page")
        icon5 = QIcon()
        iconThemeName = u"go-previous-view-page"
        if QIcon.hasThemeIcon(iconThemeName):
            icon5 = QIcon.fromTheme(iconThemeName)
        else:
            icon5.addFile(u":/icons/images/go-previous-view-page.svgz", QSize(), QIcon.Normal, QIcon.Off)

        self.actionPrevious_Page.setIcon(icon5)
        self.actionNext_Page = QAction(MainWindow)
        self.actionNext_Page.setObjectName(u"actionNext_Page")
        icon6 = QIcon()
        iconThemeName = u"go-next-view-page"
        if QIcon.hasThemeIcon(iconThemeName):
            icon6 = QIcon.fromTheme(iconThemeName)
        else:
            icon6.addFile(u":/icons/images/go-next-view-page.svgz", QSize(), QIcon.Normal, QIcon.Off)

        self.actionNext_Page.setIcon(icon6)
        self.actionContinuous = QAction(MainWindow)
        self.actionContinuous.setObjectName(u"actionContinuous")
        self.actionContinuous.setCheckable(True)
        self.actionContinuous.setChecked(True)
        self.actionBack = QAction(MainWindow)
        self.actionBack.setObjectName(u"actionBack")
        self.actionBack.setEnabled(False)
        icon7 = QIcon()
        icon7.addFile(u":/icons/images/go-previous-view.svgz", QSize(), QIcon.Normal, QIcon.Off)
        self.actionBack.setIcon(icon7)
        self.actionForward = QAction(MainWindow)
        self.actionForward.setObjectName(u"actionForward")
        self.actionForward.setEnabled(False)
        icon8 = QIcon()
        icon8.addFile(u":/icons/images/go-next-view.svgz", QSize(), QIcon.Normal, QIcon.Off)
        self.actionForward.setIcon(icon8)
        self.actionExtract_Data = QAction(MainWindow)
        self.actionExtract_Data.setObjectName(u"actionExtract_Data")
        self.actionExtract_Data.setEnabled(True)
        icon9 = QIcon()
        icon9.addFile(u":/icons/images/extract-data.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.actionExtract_Data.setIcon(icon9)
        self.actionExtract_Data.setMenuRole(QAction.MenuRole.TextHeuristicRole)
        self.actionWrite_MSTable = QAction(MainWindow)
        self.actionWrite_MSTable.setObjectName(u"actionWrite_MSTable")
        icon10 = QIcon()
        icon10.addFile(u":/icons/images/write-table.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.actionWrite_MSTable.setIcon(icon10)
        self.actionWrite_MSTable.setMenuRole(QAction.MenuRole.TextHeuristicRole)
        self.actionLoad_SalesTable = QAction(MainWindow)
        self.actionLoad_SalesTable.setObjectName(u"actionLoad_SalesTable")
        icon11 = QIcon()
        icon11.addFile(u":/icons/images/load-table.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.actionLoad_SalesTable.setIcon(icon11)
        self.actionLoad_SalesTable.setMenuRole(QAction.MenuRole.TextHeuristicRole)
        self.actionWrite_ListTable = QAction(MainWindow)
        self.actionWrite_ListTable.setObjectName(u"actionWrite_ListTable")
        icon12 = QIcon()
        icon12.addFile(u":/icons/images/write-list.svg", QSize(), QIcon.Normal, QIcon.On)
        self.actionWrite_ListTable.setIcon(icon12)
        self.actionWrite_ListTable.setMenuRole(QAction.MenuRole.TextHeuristicRole)
        self.actionLoad_MSTable = QAction(MainWindow)
        self.actionLoad_MSTable.setObjectName(u"actionLoad_MSTable")
        icon13 = QIcon()
        icon13.addFile(u":/icons/images/read-mstable.svg", QSize(), QIcon.Normal, QIcon.On)
        self.actionLoad_MSTable.setIcon(icon13)
        self.actionLoad_MSTable.setMenuRole(QAction.MenuRole.TextHeuristicRole)
        self.actionWrite_DataPdf = QAction(MainWindow)
        self.actionWrite_DataPdf.setObjectName(u"actionWrite_DataPdf")
        icon14 = QIcon()
        icon14.addFile(u":/icons/images/write-pdf.svg", QSize(), QIcon.Normal, QIcon.On)
        self.actionWrite_DataPdf.setIcon(icon14)
        self.actionWrite_DataPdf.setMenuRole(QAction.MenuRole.TextHeuristicRole)
        self.actionReadStyleConfig = QAction(MainWindow)
        self.actionReadStyleConfig.setObjectName(u"actionReadStyleConfig")
        icon15 = QIcon()
        icon15.addFile(u":/icons/images/read-config.svg", QSize(), QIcon.Normal, QIcon.On)
        self.actionReadStyleConfig.setIcon(icon15)
        self.actionReadStyleConfig.setMenuRole(QAction.MenuRole.TextHeuristicRole)
        self.centralWidget = QWidget(MainWindow)
        self.centralWidget.setObjectName(u"centralWidget")
        self.horizontalLayout_2 = QHBoxLayout(self.centralWidget)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.widget = QWidget(self.centralWidget)
        self.widget.setObjectName(u"widget")
        self.verticalLayout_2 = QVBoxLayout(self.widget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.splitter = QSplitter(self.widget)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Orientation.Horizontal)
        self.tabWidget = QTabWidget(self.splitter)
        self.tabWidget.setObjectName(u"tabWidget")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabPosition(QTabWidget.TabPosition.West)
        self.tabWidget.setDocumentMode(False)
        self.dataExtractedTab = QWidget()
        self.dataExtractedTab.setObjectName(u"dataExtractedTab")
        self.verticalLayout_4 = QVBoxLayout(self.dataExtractedTab)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.dataExtractedWidget = QTableWidget(self.dataExtractedTab)
        self.dataExtractedWidget.setObjectName(u"dataExtractedWidget")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.dataExtractedWidget.sizePolicy().hasHeightForWidth())
        self.dataExtractedWidget.setSizePolicy(sizePolicy1)
        self.dataExtractedWidget.setAutoFillBackground(False)

        self.verticalLayout_4.addWidget(self.dataExtractedWidget)

        self.tabWidget.addTab(self.dataExtractedTab, "")
        self.pumpSelectTab = QWidget()
        self.pumpSelectTab.setObjectName(u"pumpSelectTab")
        self.verticalLayout_5 = QVBoxLayout(self.pumpSelectTab)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.sourceTabWidget = QTabWidget(self.pumpSelectTab)
        self.sourceTabWidget.setObjectName(u"sourceTabWidget")

        self.verticalLayout_5.addWidget(self.sourceTabWidget)

        self.tabWidget.addTab(self.pumpSelectTab, "")
        self.dataWritenTab = QWidget()
        self.dataWritenTab.setObjectName(u"dataWritenTab")
        self.verticalLayout = QVBoxLayout(self.dataWritenTab)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.dataWritenWidget = QTableWidget(self.dataWritenTab)
        self.dataWritenWidget.setObjectName(u"dataWritenWidget")

        self.verticalLayout.addWidget(self.dataWritenWidget)

        self.tabWidget.addTab(self.dataWritenTab, "")
        self.bookmarkTab = QWidget()
        self.bookmarkTab.setObjectName(u"bookmarkTab")
        self.verticalLayout_3 = QVBoxLayout(self.bookmarkTab)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.bookmarkView = QTreeView(self.bookmarkTab)
        self.bookmarkView.setObjectName(u"bookmarkView")
        sizePolicy.setHeightForWidth(self.bookmarkView.sizePolicy().hasHeightForWidth())
        self.bookmarkView.setSizePolicy(sizePolicy)
        self.bookmarkView.setHeaderHidden(True)

        self.verticalLayout_3.addWidget(self.bookmarkView)

        self.tabWidget.addTab(self.bookmarkTab, "")
        self.splitter.addWidget(self.tabWidget)
        self.pdfView = QPdfView(self.splitter)
        self.pdfView.setObjectName(u"pdfView")
        self.pdfView.setEnabled(True)
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy2.setHorizontalStretch(10)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.pdfView.sizePolicy().hasHeightForWidth())
        self.pdfView.setSizePolicy(sizePolicy2)
        self.splitter.addWidget(self.pdfView)

        self.verticalLayout_2.addWidget(self.splitter)


        self.horizontalLayout_2.addWidget(self.widget)

        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 805, 33))
        self.menuFile = QMenu(self.menuBar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuHelp = QMenu(self.menuBar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuView = QMenu(self.menuBar)
        self.menuView.setObjectName(u"menuView")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QToolBar(MainWindow)
        self.mainToolBar.setObjectName(u"mainToolBar")
        self.mainToolBar.setMovable(False)
        self.mainToolBar.setFloatable(False)
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.mainToolBar)
        self.statusBar = QStatusBar(MainWindow)
        self.statusBar.setObjectName(u"statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExtract_Data)
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionAbout_Qt)
        self.menuView.addAction(self.actionZoom_In)
        self.menuView.addAction(self.actionZoom_Out)
        self.menuView.addAction(self.actionPrevious_Page)
        self.menuView.addAction(self.actionNext_Page)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionContinuous)
        self.mainToolBar.addAction(self.actionReadStyleConfig)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionOpen)
        self.mainToolBar.addAction(self.actionExtract_Data)
        self.mainToolBar.addAction(self.actionLoad_SalesTable)
        self.mainToolBar.addAction(self.actionWrite_MSTable)
        self.mainToolBar.addAction(self.actionWrite_ListTable)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionLoad_MSTable)
        self.mainToolBar.addAction(self.actionWrite_DataPdf)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionZoom_Out)
        self.mainToolBar.addAction(self.actionZoom_In)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionBack)
        self.mainToolBar.addAction(self.actionForward)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)
        self.sourceTabWidget.setCurrentIndex(-1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u6570\u636e\u8868\u5904\u7406\u5de5\u5177", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"\u6253\u5f00...", None))
#if QT_CONFIG(shortcut)
        self.actionOpen.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionQuit.setText(QCoreApplication.translate("MainWindow", u"\u9000\u51fa", None))
#if QT_CONFIG(shortcut)
        self.actionQuit.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionAbout_Qt.setText(QCoreApplication.translate("MainWindow", u"About Qt", None))
        self.actionZoom_In.setText(QCoreApplication.translate("MainWindow", u"\u653e\u5927", None))
#if QT_CONFIG(shortcut)
        self.actionZoom_In.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl++", None))
#endif // QT_CONFIG(shortcut)
        self.actionZoom_Out.setText(QCoreApplication.translate("MainWindow", u"\u7f29\u5c0f", None))
#if QT_CONFIG(shortcut)
        self.actionZoom_Out.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+-", None))
#endif // QT_CONFIG(shortcut)
        self.actionPrevious_Page.setText(QCoreApplication.translate("MainWindow", u"\u4e0a\u4e00\u9875", None))
#if QT_CONFIG(shortcut)
        self.actionPrevious_Page.setShortcut(QCoreApplication.translate("MainWindow", u"PgUp", None))
#endif // QT_CONFIG(shortcut)
        self.actionNext_Page.setText(QCoreApplication.translate("MainWindow", u"\u4e0b\u4e00\u9875", None))
#if QT_CONFIG(shortcut)
        self.actionNext_Page.setShortcut(QCoreApplication.translate("MainWindow", u"PgDown", None))
#endif // QT_CONFIG(shortcut)
        self.actionContinuous.setText(QCoreApplication.translate("MainWindow", u"\u9875\u9762\u8fde\u7eed", None))
        self.actionBack.setText(QCoreApplication.translate("MainWindow", u"Back", None))
#if QT_CONFIG(tooltip)
        self.actionBack.setToolTip(QCoreApplication.translate("MainWindow", u"back to previous view", None))
#endif // QT_CONFIG(tooltip)
        self.actionForward.setText(QCoreApplication.translate("MainWindow", u"Forward", None))
#if QT_CONFIG(tooltip)
        self.actionForward.setToolTip(QCoreApplication.translate("MainWindow", u"forward to next view", None))
#endif // QT_CONFIG(tooltip)
        self.actionExtract_Data.setText(QCoreApplication.translate("MainWindow", u"\u63d0\u53d6\u6570\u636e", None))
#if QT_CONFIG(shortcut)
        self.actionExtract_Data.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+E", None))
#endif // QT_CONFIG(shortcut)
        self.actionWrite_MSTable.setText(QCoreApplication.translate("MainWindow", u"\u5199\u5165\u9009\u578b\u8868", None))
#if QT_CONFIG(tooltip)
        self.actionWrite_MSTable.setToolTip(QCoreApplication.translate("MainWindow", u"\u5199\u5165\u8bbe\u5907\u9009\u578b\u8868", None))
#endif // QT_CONFIG(tooltip)
        self.actionLoad_SalesTable.setText(QCoreApplication.translate("MainWindow", u"\u52a0\u8f7d\u9500\u552e\u53f0\u8d26", None))
#if QT_CONFIG(tooltip)
        self.actionLoad_SalesTable.setToolTip(QCoreApplication.translate("MainWindow", u"\u52a0\u8f7d\u9500\u552e\u53f0\u8d26\u8868\u683c", None))
#endif // QT_CONFIG(tooltip)
        self.actionWrite_ListTable.setText(QCoreApplication.translate("MainWindow", u"\u5199\u5165\u8bbe\u5907\u4e00\u89c8\u8868", None))
#if QT_CONFIG(tooltip)
        self.actionWrite_ListTable.setToolTip(QCoreApplication.translate("MainWindow", u"\u5199\u5165\u8bbe\u5907\u4e00\u89c8\u8868", None))
#endif // QT_CONFIG(tooltip)
        self.actionLoad_MSTable.setText(QCoreApplication.translate("MainWindow", u"\u8bfb\u53d6\u6570\u636e\u9009\u578b\u8868", None))
#if QT_CONFIG(tooltip)
        self.actionLoad_MSTable.setToolTip(QCoreApplication.translate("MainWindow", u"\u8bfb\u53d6\u9009\u578b\u8868\uff0c\u51c6\u5907\u66f4\u65b0\u6570\u636e\u8868", None))
#endif // QT_CONFIG(tooltip)
        self.actionWrite_DataPdf.setText(QCoreApplication.translate("MainWindow", u"\u66f4\u65b0\u6570\u636e\u8868", None))
#if QT_CONFIG(tooltip)
        self.actionWrite_DataPdf.setToolTip(QCoreApplication.translate("MainWindow", u"\u66f4\u65b0\u6cf5\u4fe1\u606f\u5230\u6570\u636e\u8868", None))
#endif // QT_CONFIG(tooltip)
        self.actionReadStyleConfig.setText(QCoreApplication.translate("MainWindow", u"\u8bfb\u53d6\u6837\u5f0f\u914d\u7f6e", None))
#if QT_CONFIG(tooltip)
        self.actionReadStyleConfig.setToolTip(QCoreApplication.translate("MainWindow", u"\u8bfb\u53d6\u6837\u5f0f\u914d\u7f6e", None))
#endif // QT_CONFIG(tooltip)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dataExtractedTab), QCoreApplication.translate("MainWindow", u"\u6570\u636e\u63d0\u53d6", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pumpSelectTab), QCoreApplication.translate("MainWindow", u"\u6cf5\u5339\u914d\u7ed3\u679c", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dataWritenTab), QCoreApplication.translate("MainWindow", u"\u6210\u529f\u5199\u56de\u7684\u6570\u636e\u9879", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.bookmarkTab), QCoreApplication.translate("MainWindow", u"\u4e66\u7b7e", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"\u6587\u4ef6", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"\u5e2e\u52a9", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"\u67e5\u770b", None))
    # retranslateUi

